title: Nizzo
default_lang: it
author:
  name: Desegno
  email: info@desegno.it
  url: 'http://www.desegno.it/'
  taxonomies:
    - category
taxonomies:
  - category
  - tag
metadata:
  description: 'Description Meta'
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
  striptags: true
redirects: null
routes: null
blog:
  route: ''
description: 'A very delicious blog.'
global_featured_image: featured.jpg
social:
  -
    name: Facebook
    class: facebook
    url: 'http://www.facebook.com/'
  -
    name: Twitter
    class: twitter
    url: 'http://www.twitter.com/getgrav'
tel: '(+39) 06 xxxxx'
email: email@nomesito.it
cx: '43.0939952'
cy: '12.3624066'
