body_class: "stretched"
dark_mode: false
onepage: 
css:
  - 'theme://css/bootstrap.css'
  - 'theme://css/animate.css'
  - 'theme://css/magnific-popup.css'
  - 'theme://css/dark.min.css'
  - 'theme://css/padd-mr.css'
  - 'theme://css/responsive.min.css'
  - 'theme://css/font-icons.css'
  - 'theme://css/et-line.css'
  - 'theme://css/style.min.css'
  - 'theme://css/fonts.css'
  - 'theme://css/swiper.css'
  - 'theme://leaflet/leaflet.css'

inlinecss: 
fontawesome: 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
googlefont: 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700|Roboto:300,400,500,700'
sidepanel: ''
header:
  main_class: 'static-sticky '
  dark_mode: false
  sticky_dark_mode: false
